### PR TITLE
BUILD-407: Revert "remove tech preview feature gate for shared resources"

### PR DESCRIPTION
**Pull request by gabemontero**
This reverts commit 9b427d084403b0945f52f52e21b3811a2677f965.

/hold 

for a little longer, see if I can sort out hypershift req

### CODE REVIEW

**Comment by gabemontero** [comment]
unrelated flakes in optional tests, plus I could see the csi build volume tests getting skipped because tech preview was required during non-tech preview tests

also hypershift conformance is clean

/skip

/label docs-approved
/label qe-approved
/label px-approved 

@RickJWagner  - turns out changes are needed to allow for shared resources to run properly on hypershift; using a starting point provided by @sjenning I'm seeing if I can get that sorted out before 4.13 feature freeze.  If I can, we'll close this PR.  But that is most like a "stretch goal" given complexity plus my non-OCP responsibilities, and as such, we'll have to keep shared resources in tech preivew for 4.13, and we'll tag this PR for merge.  I will update https://issues.redhat.com/browse/PLMCORE-4767 with the final outcome as we get closer to feature freeze at the start of March.

And then atttach new epics/stories to https://issues.redhat.com/browse/OCPBU-228 to get things working on hypershift.

**Comment by gabemontero** [comment]
on e2e-gcp-ovn https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-storage-operator/343/pull-ci-openshift-cluster-storage-operator-master-e2e-gcp-ovn/1627678159899987968 the tests passed but the post test deprovision cluster failed 

on e2e-vsphere https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-storage-operator/343/pull-ci-openshift-cluster-storage-operator-master-e2e-vsphere/1627678159975485440 none of the 4 flakes were storage operator related 

/skip

/retest-required

**Comment by gabemontero** [comment]
more unrelated hoopla 

/test e2e-gcp-ovn

**Comment by jsafrane** [comment]
/appprove
/lgtm
(so @gabemontero does not need to wait if the revert is really needed).

**Comment by gabemontero** [comment]
thanks @jsafrane 

I will unhold this after https://github.com/openshift/openshift-controller-manager/pull/251 merges

**Comment by gabemontero** [comment]
hmm .... a 5 hours later and @jsafrane 's `/approve` from https://github.com/openshift/cluster-storage-operator/pull/343#issuecomment-1441576304 has not resulted in an approve label

/assign @dobsonj 

@jsafrane mentioned to me today he was about to start vacation (and it it close to EOB for him now).  Can you attempt to re-approve

of if I'm wrong and @jsafrane is still available, by all means 

/hold cancel

**Comment by gnufied** [comment]
There was a typo in jan's command (3ps ;-) )


/approve

**Comment by gabemontero** [comment]
> There was a typo in jan's command (3ps ;-) )
> 
> /approve

ah I missed that as well - thanks @gnufied

**Pull request merged**
