### PR TITLE
Bug 1992875: Add azure credentials

### PR DESCRIPTION
**Pull request by jsafrane**
Add credentials for Azure Disk CSI driver via cloud-credentials-operator.

In addition, pass name of cluster-cloud-controller-manager-operator image to Azure CSI driver operator, so the operator can merge cloud config + the new credentials easily (see #https://github.com/openshift/azure-disk-csi-driver-operator/pull/30).

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by bertinatto** [comment]
/hold
@jsafrane seems like you missed `10_deployment-ibm-cloud-managed.yaml`

**Comment by jsafrane** [comment]
> seems like you missed 10_deployment-ibm-cloud-managed.yaml

Good catch! Fixed.

**Comment by jsafrane** [comment]
/override e2e-aws-upgrade

I checked the failures, they do not seem to be caused by this PR.

**Comment by jsafrane** [comment]
/override ci/prow/e2e-gcp

Faulty test `crictl should be able to run crictl on the node` is getting disabled in https://github.com/openshift/origin/pull/26444.

**Pull request merged**
