### PR TITLE
Bug 2077050: OCP should default to pd-ssd disk type on GCP

### PR DESCRIPTION
**Pull request by RomanBednar**
Merge along with [PR](https://github.com/openshift/gcp-pd-csi-driver-operator/pull/47)

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
I think we should not change the storage class name. After upgrade, both `standard` and `ssd` will exist and IMO both will be default.

**Comment by RomanBednar** [comment]
> I think we should not change the storage class name. After upgrade, both `standard` and `ssd` will exist and IMO both will be default.

I've changed the patch according to our discussion and BZ comment. Same for the operator PR (linked in the description).

**Pull request merged**
