### PR TITLE
NO-JIRA: Always recreate manifests

### PR DESCRIPTION
**Pull request by stephenfin**
- ``hack: Address shellcheck issues``
- ``hack: Make HyperShift asset generation optional``
- ``hack: Always recreate manifests``

### CODE REVIEW

**Comment by stephenfin** [comment]
Pulling this out of https://github.com/openshift/cluster-storage-operator/pull/510 to see if I can isolate why the CI is unhappy with this.

**Comment by jsafrane** [comment]
@stephenfin please run `make update` to fix verify-kustomize-assets.

**Comment by stephenfin** [comment]
> @stephenfin please run `make update` to fix verify-kustomize-assets.

That's the issue: I did, and things just work, yet the job is not happy:

```
❯ git clean -xfd
Removing _output/
❯ make update
Running `gofmt -s -l -w` on 40 file(s).
Using existing yq from "_output/tools/bin/yq-2.4.0"
Using existing yaml-patch from "_output/tools/bin/yaml-patch-v0.0.11"
( echo '# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***'; _output/tools/bin/yaml-patch-v0.0.11 -o './profile-patches/hypershift/06_operator_cr.yaml-patch' < '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/06_operator_cr.yaml' ) > '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/06_operator_cr-hypershift.yaml'
( echo '# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***'; _output/tools/bin/yaml-patch-v0.0.11 -o './profile-patches/hypershift/07_service_account.yaml-patch' < '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/07_service_account.yaml' ) > '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/07_service_account-hypershift.yaml'
( echo '# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***'; _output/tools/bin/yaml-patch-v0.0.11 -o './profile-patches/hypershift/08_operator_rbac.yaml-patch' < '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/08_operator_rbac.yaml' ) > '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/08_operator_rbac-hypershift.yaml'
( echo '# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***'; _output/tools/bin/yaml-patch-v0.0.11 -o './profile-patches/hypershift/10_deployment.yaml-patch' < '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/10_deployment.yaml' ) > '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/10_deployment-hypershift.yaml'
( echo '# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***'; _output/tools/bin/yaml-patch-v0.0.11 -o './profile-patches/hypershift/11_cluster_operator.yaml-patch' < '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/11_cluster_operator.yaml' ) > '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/11_cluster_operator-hypershift.yaml'
( echo '# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***'; _output/tools/bin/yaml-patch-v0.0.11 -o './profile-patches/ibm-cloud-managed/10_deployment.yaml-patch' < '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/10_deployment.yaml' ) > '/home/stephenfin/Development/shiftstack/cluster-storage-operator/manifests/10_deployment-ibm-cloud-managed.yaml'
./hack/generate-manifests.sh
```

Am I missing something obvious, or is the job broken?

**Comment by jsafrane** [comment]
The job is broken for a long time. I can see it [reported](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-storage-operator/506/pull-ci-openshift-cluster-storage-operator-master-verify-kustomize-assets/1839403622526357504/artifacts/test/build-log.txt) the same `oc: command not found`, but ended up [green](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-storage-operator/506/pull-ci-openshift-cluster-storage-operator-master-verify-kustomize-assets/1839403622526357504) from some reason.

I'm fixing it in https://github.com/openshift/release/pull/57308

**Comment by stephenfin** [comment]
> The job is broken for a long time. I can see it [reported](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-storage-operator/506/pull-ci-openshift-cluster-storage-operator-master-verify-kustomize-assets/1839403622526357504/artifacts/test/build-log.txt) the same `oc: command not found`, but ended up [green](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-storage-operator/506/pull-ci-openshift-cluster-storage-operator-master-verify-kustomize-assets/1839403622526357504) from some reason.
> 
> I'm fixing it in [openshift/release#57308](https://github.com/openshift/release/pull/57308)

Okay, cool. I had an alternative suggestion locally, namely using `kustomize build` instead of `oc kustomize`, that I've [just pushed](https://github.com/openshift/cluster-storage-operator/pull/511/commits/d6facd8ae067e63e23ac2920eb4f894373ecfae4). wdyt about that approach instead?

**Comment by jsafrane** [comment]
/retest-required
/lgtm
/approve
/label px-approved
/label docs-approved
/label qe-approved
Not user facing, no generated yaml file has changed.

**Pull request merged**
