### PR TITLE
[4.15] OCPBUGS-29370: Update AWSCSIDriverConfigSpec fields validation to accept all curren

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/OCPBUGS-29370

This PR bumps openshift/api to pull in https://github.com/openshift/api/commit/4511c790cc60bf2a0393c34739cf9e71d1648b39

Generated with:
```
go get github.com/openshift/api@release-4.15
go mod tidy && go mod vendor
```

/cc @openshift/storage @Phaow
/label backport-risk-assessed

### CODE REVIEW

**Comment by dobsonj** [comment]
/assign @Phaow 
for cherry-pick-approved

**Comment by Phaow** [comment]
/label cherry-pick-approved
/label qe-approved
Pre verify passed with [4.15.0-0.test-2024-03-01-022849-ci-ln-9bygyp2-latest ](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1763389365179912192)`(build 4.15,openshift/cluster-storage-operator#461)`
The e2e-vsphere-csi job failed caused by install failed of CI environment issue `level=error msg=Error: failed to upload: Post "https://host-ci004.ibmvcenter.vmc-ci.devcluster.openshift.com/nfc/5229bc69-a9e2-9e4e-ce1e-b151dfeb8be0/disk-0.vmdk": dial tcp: lookup host-ci004.ibmvcenter.vmc-ci.devcluster.openshift.com on 172.30.0.10:53: server misbehaving
`
```console
$ oc edit clustercsidriver/ebs.csi.aws.com
clustercsidriver.operator.openshift.io/ebs.csi.aws.com edited 

# Use a fake aws kms key in `us-isob-east-1` region added to the clustercsidriver spec.driverConfig should be succeed
$ oc get clustercsidriver/ebs.csi.aws.com -ojsonpath='{.spec}'|jq .
{
  "driverConfig": {
    "aws": {
      "kmsKeyARN": "arn:aws-iso-b:kms:us-isob-east-1:123456789012:key/abcd1234-a123-456a-a12b-a123b4cd56ef"
    },
    "driverType": "AWS"
  },
  "logLevel": "Normal",
  "managementState": "Managed",
  "observedConfig": {
    "targetcsiconfig": {
      "servingInfo": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        ],
        "minTLSVersion": "VersionTLS12"
      }
    }
  },
  "operatorLogLevel": "Normal",
  "unsupportedConfigOverrides": null
}
```

**Pull request merged**
