### PR TITLE
Add to release payload

### PR DESCRIPTION
**Pull request by wongma7**

### CODE REVIEW

**Comment by wongma7** [comment]
@jsafrane e2e-aws passed and I see cluster-storage-operator was running https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-storage-operator/7/pull-ci-openshift-cluster-storage-operator-master-e2e-aws/14/artifacts/e2e-aws/pods/ , this is safe to merge yes? Don't want to break CI again, please review and lgtm if so!

**Comment by wongma7** [comment]
@abhinavdahiya can you confirm this is ok to merge/unhold now? sorry about #3 , don't want a repeat

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya can you confirm this is ok to merge/unhold now? sorry about #3 , don't want a repeat

Yeah looks great. Thanks :innocent: 

/lgtm

**Comment by wongma7** [comment]
/hold cancel
ty!

**Pull request merged**
