### PR TITLE
WaitForFirstConsumer in AWS StorageClass

### PR DESCRIPTION
**Pull request by wongma7**
fixes https://github.com/openshift/cluster-storage-operator/issues/11
@gnufied

### CODE REVIEW

**Comment by wongma7** [comment]
dang, seems some test can't tolerate this. will have a look monday

**Comment by gnufied** [comment]
Likely this will break in upstream too. I think nobody has run the entire e2e with just `WaitForFirstConsumer` SC. 

Lets cancel lgtm until we sort this out.

/lgtm cancel

**Comment by wongma7** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/73928 to fix the PVC protection tests. The gluster failure here looks unrelated?

**Comment by wongma7** [comment]
/test e2e-aws

(making sure gluster is a flake)

**Comment by wongma7** [comment]
the glusterdynamicprovisioner test never sets the storageclass on the claim. so it has been using the defaultstorageclass for the test!

**Comment by bertinatto** [comment]
@wongma7, if I understand correctly in order to fix the GlusterDynamicProvisioner test you just have to create a pod that uses the PVC, so the WaitForFirstConsumer mode is satisfied and the test won't timeout, right?

**Comment by wongma7** [comment]
@bertinatto yes that's one way to fix it. however, the glusterDynamicProvisioner test shouldn't be relying on the default storageclass in the first place. So by fixing that we avoid the issue

**Comment by wongma7** [comment]
/retest 
1st failure is known & being fixed, 2nd is some CNI thing? "
Feb 19 17:53:13.493: INFO: At 2019-02-19 17:53:11 +0000 UTC - event for downwardapi-volume-32f1914c-346f-11e9-b70a-0a58ac104053: {kubelet ip-10-0-165-201.ec2.internal} FailedCreatePodSandBox: Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_downwardapi-volume-32f1914c-346f-11e9-b70a-0a58ac104053_e2e-tests-downward-api-kndf7_32f3d243-346f-11e9-bca1-12f02a0bb54a_0(b3e16966fd59081bfa15ebc2c6fc5de14faee4beddeceda910a910d61f1d6f0f): Multus: Err in tearing down failed plugins: Multus: error in invoke Delegate add - "openshift-sdn": failed to Statfs "/proc/27493/ns/net": no such file or directory"

**Comment by wongma7** [comment]
/retest
install failed
level=error msg="\t* module.vpc.aws_route_table_association.route_net[4]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.route_net.4: timeout while waiting for state to become 'success' (timeout: 5m0s)"

**Comment by wongma7** [comment]
/retest
lots of issues connecting to cluster 
    Get https://api.ci-op-1mjngxdm-485da.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0: dial tcp: lookup api.ci-op-1mjngxdm-485da.origin-ci-int-aws.dev.rhcloud.com on 10.142.15.205:53: no such host
not to have occurred

**Pull request merged**
