### PR TITLE
Bug 2049872: cluster storage operator AWS credentialsrequest lacks KMS privileges

### PR DESCRIPTION
**Pull request by dobsonj**
https://bugzilla.redhat.com/show_bug.cgi?id=2049872
/hold for testing

### CODE REVIEW

**Comment by dobsonj** [comment]
/unhold
Notes from manual test:

1) Check credentialsrequest after openshift-install
```
$ oc get credentialsrequest -n openshift-cloud-credential-operator aws-ebs-csi-driver-operator -o yaml
...
    - action:
      - kms:Decrypt
      - kms:Encrypt
      - kms:GenerateDataKey
      - kms:GenerateDataKeyWithoutPlainText
      - kms:DescribeKey
      effect: Allow
      resource: '*'
    - action:
      - kms:RevokeGrant
      - kms:CreateGrant
      - kms:ListGrants
      effect: Allow
      policyCondition:
        Bool:
          kms:GrantIsForAWSResource: true
      resource: '*'
...
```

2) Create "customer managed key" in KMS via AWS console
  `arn:aws:kms:us-east-2:269733383066:alias/jdobson-kms01`
  - set jdobson and jdobson-aws-feb2022--aws-ebs-csi-driver-operator-5bq7b as key admins and users.
  - set jdobson-aws-feb2022-54m6w-master-role and jdobson-aws-feb2022-54m6w-worker-role as users.

3) Create storageclass pointing to key
```
$ cat sc-gp2-encrypted.yaml 
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi-enc
parameters:
  encrypted: "true"
  type: gp2
  kmsKeyId: arn:aws:kms:us-east-2:269733383066:alias/jdobson-kms01
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

$ oc apply -f sc-gp2-encrypted.yaml
storageclass.storage.k8s.io/gp2-csi-enc created
```

4) create PVC and Pod
```
$ cat pvc-bug2049872.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-csi
spec:
  storageClassName: "gp2-csi-enc"
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

$ oc apply -f pvc-bug2049872.yaml
persistentvolumeclaim/data-csi created

$ cat pod-busybox.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  volumes:
  - name: claim1-vol
    persistentVolumeClaim:
      claimName: data-csi
  containers:
  - image: busybox
    command:
      - "/bin/sh"
      - "-ec"
      - "touch \"/mnt/claim1/$(date -Iseconds).txt\"; sleep 604800"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
      - mountPath: "/mnt/claim1"
        name: claim1-vol
  restartPolicy: Always

$ oc apply -f pod-busybox.yaml 
pod/example created
```

5) Check PVC and Pod
```
$ oc get pods
NAME      READY   STATUS    RESTARTS   AGE
example   1/1     Running   0          27s

$ oc get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-csi   Bound    pvc-265a72c6-ad5e-4f8a-8181-2fc84ab11fa6   1Gi        RWO            gp2-csi-enc    61s

$ oc debug pod/example
Starting pod/example-debug, command was: /bin/sh -ec touch "/mnt/claim1/$(date -Iseconds).txt"; sleep 604800
Pod IP: 10.131.0.28
If you don't see a command prompt, try pressing enter.
/ # ls -l /mnt/claim1/
total 16
-rw-r--r--    1 root     root             0 Feb 28 19:36 2022-02-28T19:36:17+00:00.txt
drwx------    2 root     root         16384 Feb 28 19:36 lost+found
/ # 
```

**Comment by gnufied** [comment]
So as I understand it, encryption works for default keys and no extra permissions is needed, but if a customer wants to use different KMS key - the operator must request those permissions when creating the credentials.

**Comment by dobsonj** [comment]
> So as I understand it, encryption works for default keys and no extra permissions is needed, but if a customer wants to use different KMS key - the operator must request those permissions when creating the credentials.

Yes, correct. If the storage class has `encrypted: "true"` but no key specified, it uses the default `aws/ebs` managed key and this works without extra permissions (this is the case for the storageclasses created by the operator).
But if you provide a customer managed key, the operator needs permission to use the key.

**Pull request merged**
