### PR TITLE
manifests: add resource requests to operator pod

### PR DESCRIPTION
**Pull request by sjenning**
in service to https://github.com/openshift/origin/pull/22787

### CODE REVIEW

**Comment by gnufied** [comment]
How did we determine CPU numbers btw? I am just curious.

**Comment by sjenning** [comment]
@gnufied just looked at the Prometheus metrics for the pod

```
sort_desc(sum (rate(container_cpu_usage_seconds_total{namespace="openshift-cluster-storage-operator"}[1m])) by (pod_name))
sort_desc(sum (container_memory_usage_bytes{namespace="openshift-cluster-storage-operator"}) by (pod_name))
```
cpu
memory

**Comment by sjenning** [comment]
memory probably could have been `30Mi` but the main thing is to set something.  Something is better than nothing.

**Pull request merged**
