### PR TITLE
BUILD-407: remove tech preview feature gate for shared resources

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
e2e failures unrelated flakes, and the must gather shows shared resources successfully started in non-tech preview jobs

/retest

**Comment by gabemontero** [comment]
/hold

until https://github.com/openshift/cluster-kube-apiserver-operator/pull/1434 merges

/assign @dobsonj 
/assign @coreydaley

**Comment by gabemontero** [comment]
/assign @RickJWagner 

looking for your sign off for the px-approved label

in conjunction with work from @dobsonj from the storage team for inline csi drivers, we are looking to promote the shared resource driver from tech preview to GA for OCP as part of wrapping up https://issues.redhat.com/browse/OCPBU-228

please let me know what items you might need from me 

thanks

**Comment by gabemontero** [comment]
I've sorted out qe/docs work with @Preeticp and @jitendar-singh 

/label docs-approved
/label qe-approved

**Comment by dobsonj** [comment]
/hold for https://github.com/openshift/origin/pull/27708 to merge first
I just realized that removed test will start failing as soon as this merges

**Comment by gabemontero** [comment]
> /hold for [openshift/origin#27708](https://github.com/openshift/origin/pull/27708) to merge first I just realized that removed test will start failing as soon as this merges

ACK @dobsonj

**Comment by RickJWagner** [comment]
Hi @gabemontero ,
Thanks for highlighting this important (and anticipated) work.
Please collaborate with @coreydaley on the associated Epic.  (https://issues.redhat.com/browse/PLMCORE-4767, which is tied to the tracked Feature OCPBU-228.)
What we need:  PLMCORE-4767 has attached a slide deck, we need Engineering inputs on these.  Please collaborate to ensure we have some good content here so we can share knowledge about how this great new feature works.  
(Note:  Due date for the slides is March 3.)
Thanks for the work done here, shared resources will make users happy.

/lable px-approved

**Comment by gabemontero** [comment]
ok https://github.com/openshift/origin/pull/27708 has merged 

still waiting to see if https://github.com/openshift/cluster-kube-apiserver-operator/pull/1434 can merge before removing the hold here

**Comment by gabemontero** [comment]
releasing hold based on https://redhat-internal.slack.com/archives/CBQHQFU0N/p1675693179529159

**Pull request merged**
