### PR TITLE
Bump go to 1.19

### PR DESCRIPTION
**Pull request by jsafrane**
Based on https://github.com/openshift/cluster-storage-operator/pull/320, bump go to 1.19 and fix gofmt.

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/label docs-approved
/label px-approved

This is not user-facing change

**Comment by jsafrane** [comment]
/label qe-approved
I can see just regular flakes

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
