### PR TITLE
SPLAT-1555: Added featuregate for vSphere Multi vCenter.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1555](https://issues.redhat.com/browse/SPLAT-1555)

### Changes
- Bumped openshift/api.
- Updated operator to have permissions to featuregates

### Dependencies
- https://github.com/openshift/api/pull/1842

### Blocks
- https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/228

### CODE REVIEW

**Comment by vr4manta** [comment]
/assign @jsafrane 
This PR is ready for review. Thanks!

**Comment by jsafrane** [comment]
/label px-approved
/label docs-approved
/label qe-approved

This is not user-facing change. I expect QE + docs for the final multi-vCenter PR in vmware-vsphere-csi-driver-operator

**Pull request merged**
