### PR TITLE
STOR-1354: Remove Alibaba Disk CSI Driver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1354

This is pretty much the exact opposite of https://github.com/openshift/cluster-storage-operator/pull/239

/cc @openshift/storage
/hold for https://github.com/openshift/release/pull/47493 and https://github.com/openshift/installer/pull/7832 to merge first

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
I think you can also remove the credentials at `03_credentials_request_alibaba.yaml` and the images at image-references`.

**Comment by bertinatto** [comment]
And also the references at `ibm-cloud-managed-cleanup.yaml`.

**Comment by dobsonj** [comment]
both PR's merged
/unhold

/label px-approved
/label qe-approved
/label docs-approved

**Pull request merged**
