### PR TITLE
STOR-1839: VSphereDriverConfiguration feature Accessible-by-default

### PR DESCRIPTION
**Pull request by RomanBednar**
VSphereDriverConfiguration feature is now Accessible-by-default in 4.16: https://github.com/openshift/api/pull/1902 + https://github.com/openshift/api/pull/1904

We need to bump openshift/api and update CRD file paths in vendor.

### CODE REVIEW

**Comment by RomanBednar** [comment]
/label docs-approved
/label px-approved

Internal change only, no docs needed.

**Comment by Phaow** [comment]
/label qe-approved
Pre merge test passed with `4.17.0-0.test-2024-06-03-060358-ci-ln-sczk54b-latest (build 4.17,openshift/cluster-storage-operator#475)`

```console
 fedora@fedora35  ~  oc patch clustercsidriver/csi.vsphere.vmware.com --type=merge -p '{"spec":{"driverConfig":{"vSphere":{"granularMaxSnapshotsPerBlockVolumeInVVOL": 2}}}}'
clustercsidriver.operator.openshift.io/csi.vsphere.vmware.com patched
 fedora@fedora35  ~  oc patch clustercsidriver/csi.vsphere.vmware.com --type=merge -p '{"spec":{"driverConfig":{"vSphere":{"granularMaxSnapshotsPerBlockVolumeInVSAN": 5}}}}'
clustercsidriver.operator.openshift.io/csi.vsphere.vmware.com patched
 fedora@fedora35  ~  oc patch clustercsidriver/csi.vsphere.vmware.com --type=merge -p '{"spec":{"driverConfig":{"vSphere":{"globalMaxSnapshotsPerBlockVolume": 10}}}}'
clustercsidriver.operator.openshift.io/csi.vsphere.vmware.com patched
 fedora@fedora35  ~  oc -n openshift-cluster-csi-drivers get cm/vsphere-csi-config -o yaml
apiVersion: v1
data:
  cloud.conf: |
    # Labels with topology values are added dynamically via operator
    [Global]
    cluster-id = ocp-storage-pewang-9bbts

    [VirtualCenter "ocp-storage.vmc.qe.devcluster.openshift.com"]
    insecure-flag           = true
    datacenters             = OCP-DC
    migration-datastore-url = ds:///vmfs/volumes/657018ea-9442bafe-5f9f-b8ca3a6278ac/

    [Snapshot]
    global-max-snapshots-per-block-volume        = 10
    granular-max-snapshots-per-block-volume-vsan = 5
    granular-max-snapshots-per-block-volume-vvol = 2
kind: ConfigMap
metadata:
  creationTimestamp: "2024-06-03T10:14:54Z"
  name: vsphere-csi-config
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "94483"
  uid: 39939293-63d4-44cd-8963-aa13a1ee5a74
fedora@fedora35  ~  oc rsh vmware-vsphere-csi-driver-controller-5f47bf4c55-rbcsv cat /etc/kubernetes/vsphere-csi-config/cloud.conf
Defaulted container "csi-driver" out of: csi-driver, driver-kube-rbac-proxy, csi-provisioner, provisioner-kube-rbac-proxy, csi-attacher, attacher-kube-rbac-proxy, csi-resizer, resizer-kube-rbac-proxy, csi-snapshotter, snapshotter-kube-rbac-proxy, csi-liveness-probe, vsphere-syncer, syncer-kube-rbac-proxy
# Labels with topology values are added dynamically via operator
[Global]
cluster-id = ocp-storage-pewang-9bbts

[VirtualCenter "ocp-storage.vmc.qe.devcluster.openshift.com"]
insecure-flag           = true
datacenters             = OCP-DC
migration-datastore-url = ds:///vmfs/volumes/657018ea-9442bafe-5f9f-b8ca3a6278ac/

[Snapshot]
global-max-snapshots-per-block-volume        = 10
granular-max-snapshots-per-block-volume-vsan = 5
granular-max-snapshots-per-block-volume-vvol = 2
```

**Pull request merged**
