### PR TITLE
Remove "vmware" prefix from CSI operator and driver

### PR DESCRIPTION
**Pull request by bertinatto**
This is the third step described here: https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#removing-or-renaming-an-image-from-an-openshift-release-image

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
/retitle Remove "vmware" prefix from CSI operator and driver

**Comment by jsafrane** [comment]
I can see the CSI driver is installed in vsphere-csi job, so the PR did not break it.

**Pull request merged**
