### PR TITLE
STOR-1758: Add azure file hypershift

### PR DESCRIPTION
**Pull request by gnufied**
https://issues.redhat.com/browse/STOR-1758

### CODE REVIEW

**Comment by gnufied** [comment]
Failure on hypershift looks unrelated


/retest

**Comment by ropatil010** [comment]
/label qe-approved
Adding label based on the execution results added here: https://issues.redhat.com/browse/STOR-1704

**Comment by gnufied** [comment]
The failure in hypershift testsuite looks unrelated.

/retest

**Pull request merged**
