### PR TITLE
Install Azure Disk CSI Driver by default

### PR DESCRIPTION
**Pull request by bertinatto**
Azure Disk CSI Driver is GA in 4.10

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
for manual testing

**Comment by jsafrane** [comment]
/lgtm
Please don't forget to update our CI not to set TechPreviewNoUpgrade on Azure

**Comment by bertinatto** [comment]
> /lgtm
> Please don't forget to update our CI not to set TechPreviewNoUpgrade on Azure

https://github.com/openshift/release/pull/22102

**Pull request merged**
