### PR TITLE
Bug 1874873: Move notUpgradeable check later to prevent z-stream upgrade failures

### PR DESCRIPTION
**Pull request by huffmanca**
Moves the v1alpha1 Snapshot CRD check to later in Reconcile, so that we can proceed with z-stream upgrades.

### CODE REVIEW

**Review by wking — APPROVED** [review]

**Comment by bertinatto** [comment]
@huffmanca I noticed that the target branch is `release-4.5`; did we cherry-pick this from `master` (4.6)?

**Pull request merged**
