### PR TITLE
[4.8] Bug 2034270: Add trusted CA bundle to vsphere operators

### PR DESCRIPTION
**Pull request by jsafrane**
Use cluster's CA bundle when talking to vCenter.

Backport of #178 to 4.8

cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/lgtm cancel
the `verify` job is failing here:
```
curl -s -f -L https://github.com/krishicks/yaml-patch/releases/download/v0.0.10/yaml_patch_linux -o '_output/tools/bin/yaml-patch'
make: *** [ensure-yaml-patch] Error 22
```
This was fixed in build-machinery-go with this PR:
https://github.com/openshift/build-machinery-go/pull/58

**Comment by jsafrane** [comment]
This needs https://github.com/openshift/build-machinery-go/pull/60

**Comment by jsafrane** [comment]
Updated openshift/build-machinery-go to today's release-4.8 content.

**Pull request merged**
