### PR TITLE
OCPBUGS-11359: Remove unused versions from status

### PR DESCRIPTION
**Pull request by jsafrane**
Remove all unknown version from storage's ClusterOperator.Status.

This will clean `AWSEBSCSIDriverOperator` entry introduced in 4.8.

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
it needs https://github.com/openshift/cluster-storage-operator/pull/368 merged again (it got reverted)

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by mpatlasov** [comment]
/test e2e-aws-ovn

Prow job (https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-storage-operator/374/pull-ci-openshift-cluster-storage-operator-master-e2e-aws-ovn/1684917025169739776) reads:

```
: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) CustomResourceDefinition Should scale with a CRD targetRef [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less
--
Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_newRun #1: Failed expand_less5m42s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #0: Failed expand_less | 5m45s | {  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #1: Failed expand_less5m42s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1} | Run #1: Failed expand_less | 5m42s | {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}
Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #0: Failed expand_less | 5m45s | {  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new
Run #0: Failed expand_less | 5m45s
{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new
Run #1: Failed expand_less5m42s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1} | Run #1: Failed expand_less | 5m42s | {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}
Run #1: Failed expand_less | 5m42s
{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}

: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) CustomResourceDefinition Should scale with a CRD targetRef [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less
Run #0: Failed expand_less	5m45s
{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition
Error: exit with code 1
Ginkgo exit error 1: exit with code 1}
[open stdoutopen_in_new](https://prow.ci.openshift.org/spyglass/lens/junit/iframe?req=%7B%22artifacts%22%3A%5B%22artifacts%2Fe2e-aws-ovn%2Fgather-extra%2Fartifacts%2Fjunit%2Fjunit_install_status.xml%22%2C%22artifacts%2Fe2e-aws-ovn%2Fgather-extra%2Fartifacts%2Fjunit%2Fjunit_symptoms.xml%22%2C%22artifacts%2Fe2e-aws-ovn%2Fgather-must-gather%2Fartifacts%2Fjunit_install.xml%22%2C%22artifacts%2Fe2e-aws-ovn%2Fopenshift-e2e-test%2Fartifacts%2Fjunit%2Fjunit_e2e__20230728-140515.xml%22%2C%22artifacts%2Fe2e-aws-ovn%2Fopenshift-e2e-test%2Fartifacts%2Fjunit_node_ready.xml%22%2C%22artifacts%2Fe2e-aws-ovn%2Fopenshift-e2e-test%2Fartifacts%2Fjunit_nodes.xml%22%2C%22artifacts%2Fjunit_operator.xml%22%5D%2C%22index%22%3A2%2C%22src%22%3A%22gs%2Forigin-ci-test%2Fpr-logs%2Fpull%2Fopenshift_cluster-storage-operator%2F374%2Fpull-ci-openshift-cluster-storage-operator-master-e2e-aws-ovn%2F1684917025169739776%22%7D&topURL=https%3A//prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-storage-operator/374/pull-ci-openshift-cluster-storage-operator-master-e2e-aws-ovn/1684917025169739776&lensIndex=2#)
Run #1: Failed expand_less	5m42s
{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition
Ginkgo exit error 1: exit with code 1}
```

I can't believe it's relevant to PR, let's re-test...

**Pull request merged**
