### PR TITLE
[release-4.16] OCPBUGS-36969: STOR-1839: VSphereDriverConfiguration feature Accessible-by-default

### PR DESCRIPTION
**Pull request by RomanBednar**
This is a backport to 4.16 of https://github.com/openshift/cluster-storage-operator/pull/475

Origin backport PR https://github.com/openshift/cluster-storage-operator/pull/478 got unintentionally merged into master instead of `release-4.16` branch.

### CODE REVIEW

**Comment by Phaow** [comment]
/label qe-approved
Pre merge test passed with `4.16.0-0.test-2024-07-18-015503-ci-ln-flvfs0b-latest (build 4.16,openshift/cluster-storage-operator#491)`

```console
# The feature is accessible by default and work well

# Check the api bumped
$ oc explain clustercsidriver.spec.driverConfig.vSphere
GROUP:      operator.openshift.io
KIND:       ClusterCSIDriver
VERSION:    v1

FIELD: vSphere <Object>


DESCRIPTION:
    vsphere is used to configure the vsphere CSI driver.

FIELDS:
  globalMaxSnapshotsPerBlockVolume	<integer>
    globalMaxSnapshotsPerBlockVolume is a global configuration parameter that
    applies to volumes on all kinds of datastores. If omitted, the platform
    chooses a default, which is subject to change over time, currently that
    default is 3. Snapshots can not be disabled using this parameter. Increasing
    number of snapshots above 3 can have negative impact on performance, for
    more details see: https://kb.vmware.com/s/article/1025279 Volume snapshot
    documentation:
    https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-E0B41C69-7EEB-450F-A73D-5FD2FF39E891.html

  granularMaxSnapshotsPerBlockVolumeInVSAN	<integer>
    granularMaxSnapshotsPerBlockVolumeInVSAN is a granular configuration
    parameter on vSAN datastore only. It overrides
    GlobalMaxSnapshotsPerBlockVolume if set, while it falls back to the global
    constraint if unset. Snapshots for VSAN can not be disabled using this
    parameter.

  granularMaxSnapshotsPerBlockVolumeInVVOL	<integer>
    granularMaxSnapshotsPerBlockVolumeInVVOL is a granular configuration
    parameter on Virtual Volumes datastore only. It overrides
    GlobalMaxSnapshotsPerBlockVolume if set, while it falls back to the global
    constraint if unset. Snapshots for VVOL can not be disabled using this
    parameter.

  topologyCategories	<[]string>
    topologyCategories indicates tag categories with which vcenter resources
    such as hostcluster or datacenter were tagged with. If cluster
    Infrastructure object has a topology, values specified in Infrastructure
    object will be used and modifications to topologyCategories will be
    rejected.

# Check the configuration could be applied
$ oc patch clustercsidriver/csi.vsphere.vmware.com --type=merge -p '{"spec":{"driverConfig":{"vSphere":{"granularMaxSnapshotsPerBlockVolumeInVVOL": 2}}}}'
clustercsidriver.operator.openshift.io/csi.vsphere.vmware.com patched
$ oc patch clustercsidriver/csi.vsphere.vmware.com --type=merge -p '{"spec":{"driverConfig":{"vSphere":{"granularMaxSnapshotsPerBlockVolumeInVSAN": 5}}}}'
clustercsidriver.operator.openshift.io/csi.vsphere.vmware.com patched
$ oc patch clustercsidriver/csi.vsphere.vmware.com --type=merge -p '{"spec":{"driverConfig":{"vSphere":{"globalMaxSnapshotsPerBlockVolume": 10}}}}'
clustercsidriver.operator.openshift.io/csi.vsphere.vmware.com patched
$ oc -n openshift-cluster-csi-drivers get cm/vsphere-csi-config -o yaml
apiVersion: v1
data:
  cloud.conf: |
    # Labels with topology values are added dynamically via operator
    [Global]
    cluster-id = pewang-0718v-wg2sl

    [VirtualCenter "vcenter.devqe.ibmc.devcluster.openshift.com"]
    insecure-flag           = true
    datacenters             = DEVQEdatacenter
    migration-datastore-url = ds:///vmfs/volumes/vsan:527320283a8c3163-2faa6dc5949a3a28/

    [Snapshot]
    global-max-snapshots-per-block-volume        = 10
    granular-max-snapshots-per-block-volume-vsan = 5
    granular-max-snapshots-per-block-volume-vvol = 2
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-18T02:37:03Z"
  name: vsphere-csi-config
  namespace: openshift-cluster-csi-drivers
  resourceVersion: "78181"
  uid: 9042914b-2e0e-408e-b610-ded710a1f8d6

# Create a pvc with vsan specified storageclass and create snapshots for the volume, it is limitated by count `5` as expected
$ oc get volumesnapshots
NAME               READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS     SNAPSHOTCONTENT                                    CREATIONTIME   AGE
mypvc-snapshot-1   true         mypvc                               1Gi           csi-vsphere-vsc   snapcontent-aebcfe85-8fef-411c-93cc-0653c23e171a   13m            13m
mypvc-snapshot-2   true         mypvc                               1Gi           csi-vsphere-vsc   snapcontent-5886ce70-b3d9-4513-af51-5e09e2f840b4   12m            12m
mypvc-snapshot-3   true         mypvc                               1Gi           csi-vsphere-vsc   snapcontent-3d5e3292-99b4-4cc2-aeee-319c9f2f63fb   12m            12m
mypvc-snapshot-4   true         mypvc                               1Gi           csi-vsphere-vsc   snapcontent-ad7efaf8-199a-4e70-b2ed-41f526ddbd5b   12m            12m
mypvc-snapshot-5   true         mypvc                               1Gi           csi-vsphere-vsc   snapcontent-2afb51bc-96dc-4788-adb6-7aaa0ad7193a   12m            12m
mypvc-snapshot-6   false        mypvc                                             csi-vsphere-vsc   snapcontent-63e376b8-7716-4502-aac8-af3ec6c7e7bd                  11m
$ oc describe volumesnapshot mypvc-snapshot-6
Name:         mypvc-snapshot-6
Namespace:    default
Labels:       <none>
Annotations:  snapshot.storage.kubernetes.io/pvc-access-modes: ReadWriteOnce
              snapshot.storage.kubernetes.io/pvc-storage-class: vsan-csi-sc
              snapshot.storage.kubernetes.io/pvc-volume-mode: Filesystem
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2024-07-18T05:45:38Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:        1
  Resource Version:  90260
  UID:               63e376b8-7716-4502-aac8-af3ec6c7e7bd
Spec:
  Source:
    Persistent Volume Claim Name:  mypvc
  Volume Snapshot Class Name:      csi-vsphere-vsc
Status:
  Bound Volume Snapshot Content Name:  snapcontent-63e376b8-7716-4502-aac8-af3ec6c7e7bd
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume 0c65f6e2-2ea6-4be0-9eab-055c9b510d25: "rpc error: code = FailedPrecondition desc = the number of snapshots on the source volume 0c65f6e2-2ea6-4be0-9eab-055c9b510d25 reaches the configured maximum (5)"
    Time:        2024-07-18T05:45:39Z
  Ready To Use:  false
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  12m   snapshot-controller  Waiting for a snapshot default/mypvc-snapshot-6 to be created by the CSI driver.

```

**Comment by Phaow** [comment]
Hi @RomanBednar , BTW, I'm a bit confused why the 

> Origin backport PR https://github.com/openshift/cluster-storage-operator/pull/478 got unintentionally merged into master instead of release-4.16 branch.

I saw the https://github.com/openshift/cluster-storage-operator/pull/475/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L11 (merge to master sync with release-4.17) bump api from `github.com/openshift/api v0.0.0-20240508125607-95e22923d553` to `github.com/openshift/api v0.0.0-20240530231226-9d1c2e5ff5a8`, while even if the https://github.com/openshift/cluster-storage-operator/pull/478 target branch chooze master by mistake the git diff also shows api bump from `github.com/openshift/api v0.0.0-20240424142232-29a704bf5aa2` to `github.com/openshift/api v0.0.0-20240530231226-9d1c2e5ff5a8`. It's a bit wried. From my understanding if the target branch is not correct the diff should be no api bump right? Not sure I missed something, sorry seems I do the pre merge tests only with PR id, do not retest the 4.16 after merge. In addition I correct the e2e last month but still not merge yet, could we consider to merge it then we could found regression in CI.
https://github.com/openshift/origin/pull/28882

**Comment by RomanBednar** [comment]
@Phaow I'm not really sure how that happened but I guess it could be because the change in master merged first, then the backport PR was not rebased and merged fine (also to master) the next day. Since there was no conflict on the "backport" PR it might have merged but basically did nothing...

**Comment by Phaow** [comment]
@RomanBednar Got it, thanks for the clarify!

**Comment by Phaow** [comment]
@RomanBednar  I guess we need a fake bug which target 4.17 to let the bug valid.

**Pull request merged**
