### PR TITLE
Bug 1996672: Add proxy support to cinder CSI

### PR DESCRIPTION
**Pull request by MaysaMacedo**
Adds annotation to inject proxy env vars
to cinder-csi-driver-operator when proxy
is being used.

### CODE REVIEW

**Comment by mandre** [comment]
/retitle Bug 1996672: Add proxy support to cinder CSI

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.30

adding cherry-pick approved

**Pull request merged**
