### PR TITLE
AUTH-482: set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by liouk**

### CODE REVIEW

**Comment by liouk** [comment]
Pinned SCC to one more workload (deployment of `cluster-storage-operator`).

**Comment by jsafrane** [comment]
/lgtm

Remove WIP if it's ready to merge.

**Comment by jsafrane** [comment]
/label px-approved
/label docs-approved
This is not user-facing change.

**Comment by jsafrane** [comment]
For QE: this should result in no user visible change. It only forces the right SCCs to our components, so we avoid future issues like https://issues.redhat.com/browse/OCPBUGS-6992.

**Pull request merged**
