### PR TITLE
OCPBUGS-29126: vsphere-problem-detector: don't set Available condition

### PR DESCRIPTION
**Pull request by bertinatto**
This prevents storage to go Available=false during upgrade.

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
for manual testing.

**Comment by jsafrane** [comment]
Or even change library-go's DeploymentController to optionally not set Available condition

**Comment by bertinatto** [comment]
> Is there a way to share code with [CSIDriverOperatorDeploymentController](https://github.com/openshift/cluster-storage-operator/blob/e0c8f0bb6caf5253f97ffb098a0360197767af8a/pkg/operator/csidriveroperator/deploymentcontroller.go#L143-L143)? E.g. a common deployment controller used by both CSI operators and VPD?

This controller didn't seem a good fit because it's very specialized around CSI operator deployments. It relies a lot on objects like [CSIOperatorConfig](https://github.com/openshift/cluster-storage-operator/blob/master/pkg/operator/csidriveroperator/csioperatorclient/types.go#L18) and changing it to support VPD seemed too much effort for little benefit.

> Or even change library-go's DeploymentController to optionally not set Available condition

I did look into this, but the changes required didn't seem worth it as well.

Fortunately today is Hack'n'Hustle, so I was able to hack something up at: https://github.com/openshift/library-go/pull/1679/files

**Comment by dobsonj** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upgrade

**Comment by dobsonj** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-vsphere-ovn-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-techpreview-serial

**Comment by bertinatto** [comment]
/label docs-approved
/label px-approved
This isn't a user-facing change.

**Pull request merged**
