### PR TITLE
Bug 2108054: Allow Prometheus to scan openshift-cluster-csi-drivers namespace

### PR DESCRIPTION
**Pull request by jsafrane**
vmware-vsphere-csi-driver-operator emits metrics, so CSO must give Prometheus permissions to scan its namespace.

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
In https://github.com/openshift/cluster-storage-operator/pull/309 I tested that there is `UnsupportedCSIDriverInstalled` alert firing when the cluster is *installed* with CSIDriver instance without OCP annotation (which simulates upstream CSI driver installation).

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
