### PR TITLE
TRT-534: Add client certificate and key to service monitor

### PR DESCRIPTION
**Pull request by xueqzhan**
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md

### CODE REVIEW

**Comment by jsafrane** [comment]
@xueqzhan Can you please update also all ServiceMonitors in `assets/` directory to have also the operands covered?

**Comment by jsafrane** [comment]
/label docs-approved
/label px-approved
These changes are not user-facing.

**Comment by duanwei33** [comment]
With pre-merged PR, check some related metrics works well.

/label qe-approved

**Pull request merged**
