### PR TITLE
remove azure in-tree storage class

### PR DESCRIPTION
**Pull request by RomanBednar**
Should be merged after or along with [PR](https://github.com/openshift/azure-disk-csi-driver-operator/pull/47)

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm
/approve
/hold
https://github.com/openshift/azure-disk-csi-driver-operator/pull/47 must be merged first!

**Comment by bertinatto** [comment]
> /lgtm /approve /hold [openshift/azure-disk-csi-driver-operator#47](https://github.com/openshift/azure-disk-csi-driver-operator/pull/47) must be merged first!

openshift/azure-disk-csi-driver-operator#47 merged
/hold cancel

**Comment by bertinatto** [comment]
/hold
I want to see some azure jobs passing.

/retest

**Pull request merged**
