### PR TITLE
 Revert "Add vSphere CSI driver as tech preview"

### PR DESCRIPTION
**Pull request by stbenjam**
This reverts commit 955b99e, the image
reference is named wrong and should be vsphere-csi-driver-operator
instead.

Nightlies are currently failing:

```
error: unable to create a release: operator "cluster-storage-operator"
contained an invalid image-references file: no input image tag named
"vmware-vsphere-csi-driver-operator"
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
I think we might only want to revert https://github.com/openshift/cluster-storage-operator/pull/144/commits/955b99e8860d0d163319edf61e07f0f4b5313c64 and leave the rest.

**Comment by gnufied** [comment]
@stbenjam can you link us the failing job ?

**Comment by stbenjam** [comment]
> @stbenjam can you link us the failing job ?

Click through on any of the recent nightlies:
https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/#4.8.0-0.nightly

**Comment by stbenjam** [comment]
> I think we might only want to revert [955b99e](https://github.com/openshift/cluster-storage-operator/commit/955b99e8860d0d163319edf61e07f0f4b5313c64) and leave the rest.

Sure, updated

**Comment by gnufied** [comment]
There is also https://github.com/openshift/ocp-build-data/commit/018d2c01474e8596158767cc726d1972dd27e66f being made to fix the release. I am trying to figure out, if we need the revert or not.  cc @sosiouxme

**Comment by gnufied** [comment]
Fix the the driver image - https://github.com/openshift/ocp-build-data/pull/874

**Comment by sosiouxme** [comment]
the problem with ART builds needed to be addressed in ocp-build-data. if clayton pushes through the name change we can update it again, just let us know.

**Pull request closed without merging**
