### PR TITLE
Revert "STOR-1369: Start hypershift refactor" #384

### PR DESCRIPTION
**Pull request by xueqzhan**
Reverts openshift/cluster-storage-operator#381; tracked by [TRT-1126](https://issues.redhat.com/browse/TRT-1126)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get nightly payloads flowing again.

In the nightly payload runs, periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm has been consistently failing in the last three nightly payloads. But the run in this revert PR passed.

Here is job run example: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm/1677033031052824576.

`Storage operator Upgradable is in Unknown state. 
`

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of to confirm the fix has corrected the problem:
  `/payload 4.14 nightly blocking` 

CC: @gnufied

### CODE REVIEW

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm

**Comment by gnufied** [comment]
Can you add a link to failing job or something?

**Comment by xueqzhan** [comment]
> Can you add a link to failing job or something?

I updated the description with an example.

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn-conformance

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Pull request merged**
