### PR TITLE
OSASINFRA-3483: Prepare for openstack-manila Hypershift integration

### PR DESCRIPTION
**Pull request by stephenfin**
Rejig our asset generation and controller to prepare for a Hypershift-ful future.

This is mostly the same as the work done for openstack-cinder in #510 ~but it also depends on #513~.

**EDIT:** #513 is merged now.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
I included this two commits here https://github.com/openshift/cluster-storage-operator/pull/527
maybe we can close this PR?

**Comment by stephenfin** [comment]
> I included this two commits here #527 maybe we can close this PR?

I'll let @gnufied decide. I personally think there's value in doing this pre-work separately, but maybe it's just extra work for him :shrug:

**Comment by stephenfin** [comment]
/close

Let's focus our efforts on #527 now given the impending feature freeze.

**Pull request closed without merging**
