### PR TITLE
STOR-1722: Azure disk hypershift

### PR DESCRIPTION
**Pull request by gnufied**
https://issues.redhat.com/browse/STOR-1722

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm 
Go code looks OK, CI on azure looks green-ish and I checked azure-disk-csi-driver-operator Deployment YAML from e2e-azure-csi run here is the same as in [a previous run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-storage-operator/410/pull-ci-openshift-cluster-storage-operator-master-e2e-azure-csi/1730265765065527296).

**Comment by ropatil010** [comment]
Added the test results here: https://issues.redhat.com/browse/STOR-1707
/test e2e-ibmcloud-csi
/label qe-approved

**Pull request merged**
